---
- name: My first play
  hosts: ansible_test
  vars_files:
    - vars/vault.yml
  roles:
    - role: geerlingguy.docker
      docker_users:
        - "{{ ansible_user }}"
      become: true
    - docker-services
