services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly-iii-app
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "{{ firefly.port }}:8080"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: firefly-iii-db
    hostname: fireflyiiidb
    restart: unless-stopped
    env_file: .env
    volumes:
      - firefly_iii_db:/var/lib/mysql

volumes:
   firefly_iii_upload:
   firefly_iii_db:
