services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.11.0
    container_name: mealie
    restart: always
    ports:
      - "{{ mealie.port }}:9000"

    deploy:
      resources:
        limits:
          memory: 1000M

    environment:
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://localhost:9000
